name: brain_2th_AA_Session_First_Assignment
channels:
  - pytorch
  - conda-forge
dependencies:
  - absl-py=2.2.0
  - astunparse=1.6.3
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - colorama=0.4.6
  - cpython=3.10.16
  - filelock=3.18.0
  - flatbuffers=24.12.23
  - freetype=2.13.3
  - gast=0.6.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - google-pasta=0.2.0
  - grpcio=1.67.1
  - h2=4.2.0
  - h5py=3.13.0
  - hdf5=1.14.3
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - jinja2=3.1.6
  - keras=3.9.0
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.12.1
  - libcxx=20.1.1
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libgrpc=1.67.1
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libnghttp2=1.64.0
  - libopenblas=0.3.24
  - libpng=1.6.47
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - mdurl=0.1.2
  - ml_dtypes=0.4.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - namex=0.0.8
  - ncurses=6.5
  - networkx=3.4.2
  - numpy=2.2.4
  - openjpeg=2.5.3
  - openssl=3.4.1
  - opt_einsum=3.4.0
  - optree=0.14.1
  - packaging=24.2
  - pillow=11.1.0
  - pip=25.0.1
  - protobuf=5.28.3
  - pthread-stubs=0.4
  - pycparser=2.22
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.10.16
  - python-flatbuffers=25.2.10
  - python_abi=3.10
  - pytorch=2.5.1
  - pyyaml=6.0.2
  - re2=2024.07.02
  - readline=8.2
  - requests=2.32.3
  - rich=13.9.4
  - setuptools=75.8.2
  - six=1.17.0
  - snappy=1.2.1
  - sympy=1.13.3
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.18.0
  - tensorflow-base=2.18.0
  - tensorflow-estimator=2.18.0
  - termcolor=2.5.0
  - tk=8.6.13
  - torchvision=0.20.1
  - tqdm=4.67.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - urllib3=2.3.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wrapt=1.17.2
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.7
